---
language: node_js

sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn install -g bower
  - bower --version
  - yarn install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - yarn install --pure-lockfile
  - bower install

script:
  - yarn test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
