---
language: node_js

sudo: false
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache # includes bowers cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn add phantomjs-prebuilt
  - ./node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - yarn install --pure-lockfile --ignore-engines
  - ./node_modules/bower/bin/bower install --config.interactive=false

script:
  - yarn test:cover

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
